openapi: "3.0.3"
info:
  title: session
  version: "1.0"
servers:
  - url: "http://sessions:8081/"
paths:
  /:
    get:
      description: Getting all sessions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    tag:
                      type: string
                    description:
                      type: string
                    speaker_id:
                      type: integer
                    speaker_name:
                      type: string
                    speaker_twitter:
                      type: string
  /{id}:
    get:
      description: Getting all information about a single session
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  tag:
                    type: string
                  description:
                    type: string
                  speaker_id:
                    type: integer
                  speaker_name:
                    type: string
                  speaker_twitter:
                    type: string
        "404":
          description: ID not found
