[package]
name = "loadgenerator"
version = "0.1.1"
authors = ["Joerg Mueller <joergm@hey.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
log = "0.4"
env_logger = "0.8.3"