[package]
name = "cp-common"
version = "0.1.0"
authors = ["Joerg Mueller <joergm@hey.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
futures = "0.3"
rand = "0.8"
awc = "2.0.3" 
opentelemetry = { version = "0.12.0"}
actix-web-opentelemetry = "0.10.0"   